# Generated by Django 4.2.7 on 2025-07-15 03:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asistente_compras', '0003_shoppinglist_quality_preference'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pedido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('remitente', models.CharField(max_length=300, verbose_name='Remitente del correo')),
                ('asunto', models.CharField(max_length=300, verbose_name='Asunto del correo')),
                ('cuerpo', models.TextField(verbose_name='Cuerpo del correo')),
                ('fecha_recepcion', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de recepción')),
                ('estado', models.CharField(choices=[('nuevo', 'Nuevo'), ('procesado', 'Procesado'), ('ignorado', 'Ignorado')], default='nuevo', max_length=20, verbose_name='Estado del pedido')),
            ],
            options={
                'verbose_name': 'Pedido',
                'verbose_name_plural': 'Pedidos',
                'ordering': ['-fecha_recepcion'],
            },
        ),
    ]
